id: P003169
initial_creation_type: ocr
source_metadata:
  id: bdr:W20134
  title: མཐོ་སྒང་གི་རླུང་།
  author: ''
  volumes:
    c04a47bacdf74732995bd6e115ff15a8:
      image_group_id: I1KG22915
      title: ''
      volume_number: 1
      total_pages: 370
      base_file: v001.txt
